// src/pages/Report.jsx
// ─────────────────────────────────────────────
// SHIVANGI'S PAGE
//
// Page 4: Auto-generated audit report.
// Reads real events + score from sessionStorage
// (saved by Exam.jsx when exam ends).
// ─────────────────────────────────────────────
import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { downloadPDF } from '../services/api.js'
import styles from './Report.module.css'

function Report() {
  const navigate = useNavigate()
  const [events,    setEvents]    = useState([])
  const [riskScore, setRiskScore] = useState(0)

  // Load data saved by Exam.jsx
  useEffect(() => {
    const savedEvents = sessionStorage.getItem('examEvents')
    const savedScore  = sessionStorage.getItem('examRiskScore')
    if (savedEvents) setEvents(JSON.parse(savedEvents))
    if (savedScore)  setRiskScore(parseInt(savedScore))
  }, [])

  // Verdict based on score
  const verdict =
    riskScore < 30 ? 'clear' :
    riskScore < 70 ? 'review' : 'flagged'

  const verdictColor = { clear:'var(--safe)', review:'var(--warn)', flagged:'var(--danger)' }[verdict]
  const verdictTitle = { clear:'✓ EXAM CLEARED', review:'⚠ FLAGGED FOR REVIEW', flagged:'✕ HIGH RISK — REVIEW REQUIRED' }[verdict]
  const verdictDesc  = {
    clear:   `Risk score of ${riskScore} is within acceptable threshold. Behavioral signals were evaluated as non-suspicious. No human review required.`,
    review:  `Risk score of ${riskScore} requires manual review. ${events.length} behavioral signals detected. Contextual analysis suggests possible irregularities.`,
    flagged: `Risk score of ${riskScore} significantly exceeds threshold. ${events.length} events logged. Immediate institutional review required.`
  }[verdict]

  // Count by type
  const count = (type) => events.filter(e => e.event_type === type).length

  function handleDownload() {
    // Try API first, fall back to text file
    downloadPDF('IL-2026-00342').catch(() => {
      const lines = [
        'INTEGRITYLENS AI — AUDIT REPORT',
        '================================',
        'Candidate: Mukesh R.',
        'Exam: CS-401 Algorithms',
        'Date: 28 Feb 2026',
        `Risk Score: ${riskScore}/100`,
        `Verdict: ${verdictTitle}`,
        '',
        'EVENT TIMELINE:',
        ...events.map(e => `[${e.timestamp}] ${e.label} — ${e.severity} (conf: ${parseFloat(e.confidence).toFixed(2)})`),
        '',
        `Total Events: ${events.length}`,
        'Generated by IntegrityLens AI — BUILDX 2026',
      ]
      const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
      const url  = URL.createObjectURL(blob)
      const a    = document.createElement('a')
      a.href = url; a.download = 'IntegrityLens_Report.txt'; a.click()
      URL.revokeObjectURL(url)
    })
  }

  return (
    <div className={`${styles.page} page-enter`}>
      <div className={styles.container}>

        {/* Top heading */}
        <div className={styles.top}>
          <div className={styles.heading}>AUDIT<br /><span>REPORT</span></div>
          <div className={styles.meta}>
            <div className={styles.metaLine}>CANDIDATE: <strong>MUKESH R.</strong></div>
            <div className={styles.metaLine}>EXAM: <strong>CS-401 ALGORITHMS</strong></div>
            <div className={styles.metaLine}>DATE: <strong>28 FEB 2026</strong></div>
            <div className={styles.metaLine}>SESSION: <strong className={styles.sessionId}>IL-2026-00342</strong></div>
          </div>
        </div>

        {/* Verdict banner */}
        <div className={`${styles.verdict} ${styles[verdict]}`}>
          <div className={styles.verdictScore} style={{ color: verdictColor }}>
            {riskScore}
          </div>
          <div className={styles.verdictInfo}>
            <div className={styles.verdictTitle} style={{ color: verdictColor }}>{verdictTitle}</div>
            <div className={styles.verdictDesc}>{verdictDesc}</div>
          </div>
        </div>

        {/* Two-column detail */}
        <div className={styles.grid}>
          {/* Signal breakdown */}
          <div className={styles.card}>
            <div className={styles.cardTitle}>SIGNAL BREAKDOWN</div>
            <div className={styles.breakdown}>
              {[
                { label:'Tab Switches',     type:'TAB_SWITCH',        color:'var(--warn)' },
                { label:'Gaze Deviations',  type:'GAZE_DEVIATION',    color:'var(--accent)' },
                { label:'Multiple Faces',   type:'MULTIPLE_FACES',    color:'var(--danger)' },
                { label:'Audio Spikes',     type:'AUDIO_SPIKE',       color:'var(--warn)' },
                { label:'Face Lost',        type:'FACE_NOT_DETECTED', color:'var(--danger)' },
              ].map(row => {
                const c = count(row.type)
                const pct = Math.min(c * 20, 100)
                return (
                  <div key={row.type} className={styles.breakRow}>
                    <span className={styles.breakName}>{row.label}</span>
                    <div className={styles.breakBar}>
                      <div className={styles.breakFill} style={{ width: pct + '%', background: row.color }} />
                    </div>
                    <span className={styles.breakCount}>{c}</span>
                  </div>
                )
              })}
            </div>

            <div className={styles.formula}>
              <div className={styles.formulaLabel}>RISK FORMULA</div>
              <div className={styles.formulaText}>
                Score = Σ (Weight × Duration<br />× Confidence × Context Modifier)
              </div>
            </div>
          </div>

          {/* Event timeline */}
          <div className={styles.card}>
            <div className={styles.cardTitle}>EVENT TIMELINE</div>
            <div className={styles.timeline}>
              {events.length === 0 ? (
                <div className={styles.noEvents}>No events recorded — clean exam session.</div>
              ) : (
                events.map((ev, i) => (
                  <div key={i} className={`${styles.timelineItem} ${ev.severity === 'HIGH' ? styles.tlHigh : styles.tlLow}`}>
                    <div className={styles.tlTime}>{ev.timestamp}</div>
                    <div className={styles.tlBody}>
                      <div className={styles.tlEvent}>{ev.label}</div>
                      <div className={styles.tlDetail}>
                        Conf: {parseFloat(ev.confidence).toFixed(2)} · Sev: {ev.severity} · {ev.duration}s
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className={styles.actions}>
          <button className={`btn btn-primary`} onClick={handleDownload}>↓ Download PDF Report</button>
          <button className={`btn btn-outline`} onClick={() => navigate('/monitor')}>← Back to Dashboard</button>
          <button className={`btn btn-outline`} onClick={() => navigate('/verify')}>↺ New Session</button>
        </div>

      </div>
    </div>
  )
}

export default Report
